apiVersion: v1
kind: Service
metadata:
  name: kube-test-node-service
spec:
  selector:
    app: kube-test-node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
