name: Create Release Tag

on:
  repository_dispatch:
    types: [create-release-tag]

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_RUN_ID: ${{ github.event.client_payload.workflow_run_id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set release variables
        run: |
          # Set your release variables here

      - name: Create release & tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MY_PROJECT_TOKEN }}
          script: |
            # Your script to create a release and tag

      - name: Trigger Change Log
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.MY_PROJECT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/anujm4467/github-workflow-play/dispatches \
            -d '{"event_type": "generate-change-log", "client_payload": {"workflow_run_id": '${{ github.run_id }}'}}'
