name: Create Release Tag

on:
  repository_dispatch:
    types: [create-release-tag]

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_RUN_ID: ${{ github.event.client_payload.workflow_run_id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Approvals data
        uses: actions/github-script@v7
        id: get-approvals-data
        with:
          github-token: ${{ secrets.MY_PROJECT_TOKEN }}
          result-encoding: string
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            try {
              const result = await github.rest.actions.getReviewsForRun({
                run_id: process.env.WORKFLOW_RUN_ID,
                owner: owner,
                repo: repo,
              });

              const users = [...new Set(result.data.map(({ user }) => user.login))];
              if (users.length > 0) {
                return users.join(", ");
              } else {
                const errorMsg = "The build process hasn't been approved yet.";
                throw new Error(errorMsg);
              }
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Generate Change Log
        run: |
          # Your script to generate the change log based on commit titles and hashes
          echo "Your change log content" > change-log.txt

      - name: Upload Change Log
        uses: actions/upload-artifact@v2
        with:
          name: change-log
          path: ./change-log.txt

      - name: Set release variables
        run: |
          RELEASE_NAME="DM Web Release"
          RELEASE_TAG="rel_$(date "+%y_%m_%d_12")_dm"
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Create release & tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MY_PROJECT_TOKEN }}
          script: |
            const body = [
              process.env.RELEASE_NAME,
              'Job initiated at ' + new Date().toLocaleString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' }).replace(/[,:]/g, (match) => match === ',' ? ' ' : ':'),
            ];

            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_NAME,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
                body: body.join('\r\n'),
              });
            } catch (error) {
              core.setFailed(error.message);
            }
