name: Create Release Tag

on:
  repository_dispatch:
    types: [create-release-tag]

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_RUN_ID: ${{ github.event.client_payload.workflow_run_id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set release variables
        run: |
          RELEASE_NAME="DM Web Release"
          RELEASE_TAG="rel_$(date "+%y_%m_%d")_dm"
          # Add other release variables as needed

          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Create release & tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MY_PROJECT_TOKEN }}
          script: |
            const body = [
              process.env.RELEASE_NAME,
              'Job initiated at ' + new Date(),
              // Add other release information
            ];

            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_NAME,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
                body: body.join('\r\n'),
              });
            } catch (error) {
              core.setFailed(error.message);
            }
