name: Workflow1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      matrix:
        include:
          my_data: Hello from Workflow1

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set outputs
        id: set_outputs
        run: echo "my_data=${{ matrix.my_data }}" >> $GITHUB_ENV
