name: Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set URL variable
        run: echo "TEST_URL=https://dubtest.idealite.in" >> $GITHUB_ENV

      - name: Display URL
        run: echo "Test URL is $TEST_URL"
