name: Trigger Generate Change Log

on:
  repository_dispatch:
    types:
      - create-release-tag

jobs:
  trigger-generate-change-log:
    runs-on: ubuntu-latest
    steps:
      - name: Check Payload
        run: |
          echo "Event payload: $GITHUB_EVENT_PATH"
          cat $GITHUB_EVENT_PATH

      - name: Trigger Generate Change Log
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MY_PROJECT_TOKEN }}
          script: |
            try {
              // Extract necessary information from the payload
              const workflowRunID = github.context.payload.workflow_run.id;

              if (!workflowRunID) {
                console.log("Workflow run ID not found. Exiting.", github.context.payload);
                return;
              }

              // Trigger the Generate Change Log workflow
              const response = await github.actions.createWorkflowDispatch({
                owner: 'anujm4467', // Change to your repository owner
                repo: 'github-workflow-play', // Change to your repository name
                workflow_id: 'generate-change-log.yml', // Adjust the workflow filename
                ref: 'main', // Change to your branch name
                inputs: {
                  workflow_run_id: workflowRunID.toString(),
                },
              });

              console.log(`Generate Change Log workflow triggered: ${response.status}`);
            } catch (error) {
              core.setFailed(error.message);
            }
